# Generated by Django 4.1 on 2022-10-26 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_feedback_feedbackreply"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        max_length=120, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "pending"),
                            ("Completed", "completed"),
                            ("Failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("mode", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
