# Generated by Django 4.1.2 on 2022-10-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_categorymodel_image_alter_productmodel_image_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Address",
            new_name="AddressModel",
        ),
        migrations.RenameModel(
            old_name="CartItem",
            new_name="CartItemModel",
        ),
        migrations.RenameModel(
            old_name="Cart",
            new_name="CartModel",
        ),
        migrations.RenameModel(
            old_name="Feedback",
            new_name="FeedbackModel",
        ),
        migrations.RenameModel(
            old_name="FeedbackReply",
            new_name="FeedbackReplyModel",
        ),
        migrations.RenameModel(
            old_name="Location",
            new_name="LocationModel",
        ),
        migrations.RenameModel(
            old_name="Order",
            new_name="OrderModel",
        ),
        migrations.RenameModel(
            old_name="Payment",
            new_name="PaymentModel",
        ),
        migrations.RenameModel(
            old_name="Profile",
            new_name="ProfileModel",
        ),
    ]
