# Generated by Django 4.1 on 2022-11-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_profilemodel_address_profilemodel_addresses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="dob",
            field=models.DateField(null=True),
        ),
    ]
